jobs:
  include:
    - language: java
      before_script:
        - cd dota-parser-master
        - mkdir -p ../build/data/
      script: 
        - mvn package
        - java -jar target/dota-parser-1.0.jar ../build/replays/test

    - language: python
      python:
        - "3.6"
      before_install:
        - cd dota-parser-master
        - mkdir -p ../build/data/
        - mvn package
        - java -jar target/dota-parser-1.0.jar ../build/replays/test
        - cd ..
        - mkdir -p build/data/{mouseaction,mousesequence,playerstats,iteminfo}
        - mkdir -p build/dfs
        - sh move_data.sh build/data
      install:
        - pip install -r learning/requirements.txt
      before_script:
        - cd learning/src
      script:
        - python run_move_classifier.py ../../build/data/mouseaction 2 76561198019729122
        - python run_game_classifier.py ../../build/data/mouseaction 2 76561198019729122
        - python create_featureset.py ../../build/data/mouseaction ../../build/dfs
        - python run_pair_classifier.py ../../build/dfs 2

    - before_script:
        - cd report/
      script:
        - latexmk -pdf Report.tex
      
