* 18/09/18
First meeting to discuss project. Main idea of the project is to predict who the player is in a game of DOTA based on replay data. 

** Initial plan (technical)
Start with parsing mouse movement from replays using ~clarity~ or the python replay parser to get angles/curves. 
- http://www.ise.bgu.ac.il/faculty/liorr/clint1.pdf

Start with the same player on the same hero using binary classification - is the player playing this hero X or not?

Further game knowledge prediction features later and predict with features both independently and combined

Other ideas:
- Predicting strategies of players

- tracking statistics for pro players
- detect previously banned players
- anonymity in online games leading to antisocial behaviour due to lack of consequences > easily make new accounts to continue behaviour despite bans, especially in free to play games
- smurfing ranked games affecting players at lower skill level
- elo boosting and selling high ranked accounts (hard to detect)
- use case of 'stolen' accounts, where player behaviour suddenly changes to be very different
- 'identity theft' in online amateur tournaments

* 27/09/18
** Before meeting notes
DOER:
- need to add objective about identifying features to extract from replays?

Parser:


** TODO next week
 - [x] Auto replay download with OpenDOTA API
 - [x] Get player entity given steamID
 - [x] Parse player mouse movement data in ML friendly format
 - [] Process mouse movement data for ML based on identification paper
 - [] Run ML on dataset of mouse movement data

** Other notes
- Might need to get ethics approval

This project aims to predict players in the video game Dota 2 by analysing replays of players and running the data through a machine learning model. The purpose is to detect players using accounts for illegitimate reasons such as account selling. Publicly available data from Dota 2 players will be collected from the internet and processed. The research will be done in St Andrews and no interaction between the researcher and the players will take place.

- not interested in personal name, just interested in matching the account ids together
- not possible to obtain consent
- getting data from valve not opendota
- potential for identifiable names, but not interested, so will not store account names only ids
- say more about why, detect whether its the same person behind the account
- how long to keep the data, not going to store user id, analysed data kept indefinitely, anonimysed by removal of handle names

- steam API key = FFF909F2C1F90CFD66D568D188DBF371

* 04/10/18

** TODO week
- [] Process mouse movement data for ML with categorised features
- [] Setup ML pipeline
