* 18/09/18
First meeting to discuss project. Main idea of the project is to predict who the player is in a game of DOTA based on replay data. 

** Initial plan (technical)
Start with parsing mouse movement from replays using ~clarity~ or the python replay parser to get angles/curves. 
- http://www.ise.bgu.ac.il/faculty/liorr/clint1.pdf

Start with the same player on the same hero using binary classification - is the player playing this hero X or not?

Further game knowledge prediction features later and predict with features both independently and combined

Other ideas:
- Predicting strategies of players

- tracking statistics for pro players
- detect previously banned players
- anonymity in online games leading to antisocial behaviour due to lack of consequences > easily make new accounts to continue behaviour despite bans, especially in free to play games
- smurfing ranked games affecting players at lower skill level
- elo boosting and selling high ranked accounts (hard to detect)
- use case of 'stolen' accounts, where player behaviour suddenly changes to be very different
- 'identity theft' in online amateur tournaments

* 27/09/18
** Before meeting notes
DOER:
- need to add objective about identifying features to extract from replays?

Parser:

